---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqlpv 
  namespace: db-hosts
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /data/sqlvol1/


---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sqlpvclaim
  namespace: db-hosts
spec:
  storageClassName: standard 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: sql
  namespace: db-hosts
  labels:
    app: sql
spec:
  volumes:
    - name: sqlvol 
      persistentVolumeClaim:
        claimName: sqlpvclaim
  containers:
    - image: ericskang/demodb:mssql
      name: mssql
      imagePullPolicy: Always
      env:
        - name: ACCEPT_EULA
          value: "Y"
      volumeMounts:
        - mountPath: /var/opt/mssql
          name: sqlvol
---

kind: Service
apiVersion: v1
metadata:
  name: sql
  namespace: db-hosts
spec:
  selector:
    app: sql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: NodePort

--- 
