version: '3'
services:
  slacker:
    image: ericskang/slacker-node-runner:latest
    depends_on: 
      - mssql
    command: ["npm", "start"] # make slacker runner container up and running
    container_name: slacker_runner
    ports:
      - "8000:8000"
  mssql:
    image: sqldevopsacs.azurecr.io/wwi_test:latest
    container_name: mssql_unittest
    ports: 
      - "1433:1433"
    environment:
      SA_PASSWORD: "Yukon900"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Developer