version: '3'
services:
  slacker:
    build: .
    depends_on: 
      - mssql
    container_name: slacker_runner
    ports:
      - "80:8000"
  mssql:
    build: ./unittest_db
    container_name: mssql_unittest
    ports: 
      - "1433:1433"
    environment:
      SA_PASSWORD: "Yukon900"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Developer