apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: basic-ingress
  namespace: sqldevops
spec:
  rules:
  - http:
      paths:
      - path: /api
        backend:
          serviceName: slacker
          servicePort: 8000
