apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: slacker-runner
spec:
  template:
    metadata:
      labels:
        app: slacker-runner
    spec:
      containers:
      - image: sqldevopsacs.azurecr.io/slacker-node-runner:latest
        name: slacker-runner
        imagePullPolicy: Always
        ports:
          - containerPort: 8000
      imagePullSecrets:
        - name: mssqlkey
      #   todo: persistent volumemounting
      #   volumeMounts:
      #   - name: mssql-persistent-storage
      #     mountPath: /var/opt/mssql
      # volumes:
      # - name: mssql-persistent-storage
      #   persistentVolumeClaim:
      #     claimName: mssql-pv-claim