apiVersion: v1
kind: Service
metadata:
  name: slacker-runner
  labels:
    app: slacker-runner
spec:
  type: LoadBalancer
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: slacker-runner