---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqlpv 
  namespace: production
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Recycle 
  nfs:
    path: "/k8svolumes"
    server: "10.135.10.138"
