---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlpvclaim3
  namespace: production
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi