apiVersion: batch/v1
kind: Job
metadata:
  name: db-provisioning
  namespace: db-hosts
spec:
  template:
    metadata:
      name: db-provisioning
    spec:
      containers:
      - name: db-provisioning
        image: ericskang/db-provision-job
        command:
         - "bin/bash"
         - "-c"
         - "provision.sh"
      restartPolicy: Never