---
apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: sql-full-backup-job
  namespace: db-hosts
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: sql-full-backup-job
            image: ericskang/cronjobs:backup
            imagePullPolicy: Always
            args:
            - /bin/bash
            - -c
            - ./full-backup.sh
          restartPolicy: OnFailure

---
apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: sql-log-backup-job
  namespace: db-hosts
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: sql-log-backup-job
            image: ericskang/cronjobs:backup
            imagePullPolicy: Always
            args:
            - /bin/bash
            - -c
            - ./log-backup.sh
          restartPolicy: OnFailure