kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sqlpvclaim
  namespace: production
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi 
