---
apiVersion: v1
kind: Pod
metadata:
  name: mssql
  namespace: production
  labels:
    app: mssql
spec:
  volumes:
    - name: sqlvol 
      persistentVolumeClaim:
        claimName: sqlpvclaim
  containers:
    - image: microsoft/mssql-server-linux:latest
      name: mssql
      env:
        - name: "ACCEPT_EULA"
          value: "Y"
      env:
        - name: "SA_PASSWORD"
          value: "SqlDevOps2017"
      env:
        - name: "MSSQL_PID"
          value: "Developer"
      volumeMounts:
        - mountPath: /var/opt/mssql
          name: sqlvol
---

kind: Service
apiVersion: v1
metadata:
  name: mssql
  namespace: production
spec:
  selector:
    app: mssql
  ports:
    - protocol: TCP
      port: 1433
      nodePort: 31433
      targetPort: 1433
  type: NodePort

--- 
