---
apiVersion: batch/v2alpha1
kind: Job
metadata:
  name: db-migration-job
  namespace: sqldevops
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: db-migration-job
            image: ericskang/db-jobs:migration
            args:
            - /bin/bash
            - -c
            - ./log-backup.sh
          restartPolicy: OnFailure