---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs 
  namespace: production
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain 
  nfs:
    path: "/export"
