---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs 
  namespace: production
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Recycle 
  nfs:
    path: "/export"
    server: "192.168.1.119"
