apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mssql
  namespace: sqldevops
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mssql
    spec:
      containers:
      - image: sqldevopsacs.azurecr.io/mssql
        name: mssql
        imagePullPolicy: Always
        ports:
          - containerPort: 1433
            name: mssql
      imagePullSecrets:
        - name: mssqlkey
      #   todo: persistent volumemounting
      #   volumeMounts:
      #   - name: mssql-persistent-storage
      #     mountPath: /var/opt/mssql
      # volumes:
      # - name: mssql-persistent-storage
      #   persistentVolumeClaim:
      #     claimName: mssql-pv-claim