---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgsqlpv 
  namespace: db-hosts
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/pgsqlvol1/

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pgsqlpvclaim
  namespace: db-hosts
spec:
  storageClassName: standard 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: pgsql
  namespace: db-hosts
  labels:
    app: pgsql
spec:
  volumes:
    - name: pgsqlvol 
      persistentVolumeClaim:
        claimName: pgsqlpvclaim
  containers:
    - image: ericskang/demodb:pgsql
      name: pgsql
      imagePullPolicy: Always
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: pgsqlvol
---

kind: Service
apiVersion: v1
metadata:
  name: pgsql
  namespace: db-hosts
spec:
  selector:
    app: pgsql
  ports:
    - protocol: TCP
      port: 5432
      nodePort: 32432
      targetPort: 5432
  type: NodePort

--- 
